name: "sample React CI pipeline / workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        run-on: ubuntu-latest

        steps:
            - name: "setup Node JS"
              uses: action/setup-node@v4
              with:
                node-version: '21'
                