name: "sample React CI pipeline / workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: "check node version"
        run: node --version
